"""
Central configuration for the Celtics Real-Time Win Probability project.

Every path, season, and constant used anywhere in the pipeline is defined here
and imported. Nothing else in the codebase should hard-code a path or a season.

Reference: Directed Research Registration Form 2025, "Celtics Real-Time Win
Probability Model", Prof. Ahmad Namini.
"""

from pathlib import Path

# ----------------------------------------------------------------------------
# Paths
# ----------------------------------------------------------------------------
# PROJECT_ROOT resolves to the celtics_wp folder regardless of where a script
# is launched from, so running inside Spyder and running from a terminal both
# resolve to the same place.
PROJECT_ROOT = Path(__file__).resolve().parent.parent

DATA_DIR = PROJECT_ROOT / "data"
RAW_DIR = DATA_DIR / "raw"           # exactly what the API returned, never edited
INTERIM_DIR = DATA_DIR / "interim"   # parsed but not yet feature-engineered
PROCESSED_DIR = DATA_DIR / "processed"  # model-ready tables

MODELS_DIR = PROJECT_ROOT / "models"
REPORTS_DIR = PROJECT_ROOT / "reports"
LOGS_DIR = PROJECT_ROOT / "logs"
FIGURES_DIR = PROJECT_ROOT / "figures"   # paper figures, regenerated on demand
SERVING_DIR = DATA_DIR / "serving"       # precomputed JSON the dashboard reads

# Raw subfolders, one per endpoint, so provenance stays obvious on disk.
RAW_PBP_DIR = RAW_DIR / "playbyplay"
RAW_BOX_DIR = RAW_DIR / "boxscore"

ALL_DIRS = [
    DATA_DIR, RAW_DIR, INTERIM_DIR, PROCESSED_DIR,
    MODELS_DIR, REPORTS_DIR, LOGS_DIR, FIGURES_DIR, SERVING_DIR,
    RAW_PBP_DIR, RAW_BOX_DIR,
]


def ensure_dirs():
    """Create every project directory if it does not already exist."""
    for d in ALL_DIRS:
        d.mkdir(parents=True, exist_ok=True)


# ----------------------------------------------------------------------------
# Scope
# ----------------------------------------------------------------------------
# Boston Celtics franchise ID in the NBA stats API. This is a stable identifier.
CELTICS_TEAM_ID = 1610612738
CELTICS_ABBREV = "BOS"

# The eight seasons specified in the research plan: 2016-17 through 2023-24.
SEASONS = [
    "2016-17",
    "2017-18",
    "2018-19",
    "2019-20",
    "2020-21",
    "2021-22",
    "2022-23",
    "2023-24",
]

SEASON_TYPE = "Regular Season"

# Expected regular season game counts for Boston, used as a validation check.
# 82 games in a normal season. 2019-20 was cut short by the COVID-19 suspension
# and Boston played 72. 2020-21 was a scheduled 72-game season league-wide.
# These are EXPECTATIONS TO TEST, not values to force the data to match. If the
# pull disagrees, the difference gets investigated and documented.
EXPECTED_GAME_COUNTS = {
    "2016-17": 82,
    "2017-18": 82,
    "2018-19": 82,
    "2019-20": 72,
    "2020-21": 72,
    "2021-22": 82,
    "2022-23": 82,
    "2023-24": 82,
}
EXPECTED_TOTAL_GAMES = sum(EXPECTED_GAME_COUNTS.values())  # 636

# ----------------------------------------------------------------------------
# Reproducibility
# ----------------------------------------------------------------------------
RANDOM_SEED = 20261730

# ----------------------------------------------------------------------------
# Network behaviour for nba_api calls
# ----------------------------------------------------------------------------
# stats.nba.com is rate sensitive and will start returning timeouts or empty
# payloads if hit too fast. These values are deliberately conservative: a slow
# successful pull is worth far more than a fast pull with silent gaps.
REQUEST_TIMEOUT = 60      # seconds passed to the endpoint
REQUEST_DELAY = 0.8       # seconds to sleep between successful calls
MAX_RETRIES = 4           # attempts per call before recording a failure
RETRY_BACKOFF = 3.0       # seconds, multiplied by attempt number


# ----------------------------------------------------------------------------
# Canonical file locations
# ----------------------------------------------------------------------------
GAME_INDEX_CSV = RAW_DIR / "game_index.csv"
RAW_MANIFEST_CSV = RAW_DIR / "raw_pull_manifest.csv"

# Registry of data anomalies that have been INVESTIGATED, VERIFIED against an
# independent source, and consciously accepted. This file is generated by the
# diagnostic scripts from real API responses. It is never hand-edited, because a
# hand-typed registry is a place for transcription errors to hide, and because a
# whitelist nobody can audit is worse than a failing check.
#
# Every row must carry its evidence and its verification source. The audit
# prints the contents in full rather than silently skipping the games.
KNOWN_ANOMALIES_CSV = DATA_DIR / "known_data_anomalies.csv"

# Phase 2 outputs. Parsed, not raw: every one of these is rebuildable from
# data/raw by re-running the Phase 2 scripts.
EVENTS_PARQUET = INTERIM_DIR / "events.parquet"
ROSTERS_PARQUET = INTERIM_DIR / "rosters.parquet"
LINEUPS_PARQUET = INTERIM_DIR / "lineups.parquet"
LINEUP_ANOMALIES_CSV = INTERIM_DIR / "lineup_anomalies.csv"
DERIVED_MINUTES_CSV = INTERIM_DIR / "derived_minutes.csv"

# Games whose player-level plus/minus does not reconcile against the final
# margin. These are AT RISK for lineup reconstruction, which is a different thing
# from the excusal registry above, so they are recorded separately. Being listed
# here excuses nothing.
LINEUP_RISK_CSV = DATA_DIR / "lineup_risk_games.csv"

# Phase 3 output: the model-ready event table with live game-state features.
# Lineup strength is deliberately NOT in this file. It is an aggregate over games
# and must be computed inside each cross-validation fold from training seasons
# only, so baking it in here would make leakage easy and invisible.
MODEL_FRAME_PARQUET = PROCESSED_DIR / "model_frame.parquet"

# Regulation length in seconds, for time-remaining features.
REGULATION_SECONDS_TOTAL = 4 * 12 * 60   # 2880


if __name__ == "__main__":
    ensure_dirs()
    print("Project root:", PROJECT_ROOT)
    print("Seasons:", len(SEASONS), "->", SEASONS[0], "to", SEASONS[-1])
    print("Expected total regular season games:", EXPECTED_TOTAL_GAMES)
    print("Directories ready.")
