"""
The documented data anomaly registry.

What this is for
----------------
Real historical data has real defects. A research pipeline needs somewhere to
record "we found this, we investigated it, here is the evidence, here is why it
does not invalidate the analysis" so that the defect is neither hidden nor
allowed to block every future run.

What this is NOT for
--------------------
Making failing checks pass. Three rules keep it honest:

  1. The registry is GENERATED by diagnostic scripts from real API responses.
     It is never hand-typed. Hand transcription is where invented values creep
     in, and an invented game ID in a whitelist would silently exempt the wrong
     game.

  2. Every row must carry a verification source and a verification date. A row
     without evidence is rejected on load, not quietly trusted.

  3. The audit prints the registry in full. A reader of the validation report
     sees exactly which games were excused and why. Nothing is skipped silently.

Anything not in the registry that violates a check is still a hard failure.
"""

import pandas as pd

from src import config

REQUIRED_COLUMNS = [
    "game_id", "game_date", "matchup", "column", "issue",
    "reported_value", "verification_source", "verified_on", "resolution",
]


class AnomalyRegistryError(RuntimeError):
    """Raised when the registry file exists but is not trustworthy."""


def load_anomalies() -> pd.DataFrame:
    """
    Load the registry, or return an empty frame if it does not exist yet.

    Raises AnomalyRegistryError if the file exists but is missing required
    evidence columns or has rows without a verification source. A malformed
    registry must fail loudly; treating it as empty would turn a broken audit
    trail into a silently stricter audit, and treating it as valid would exempt
    games on no evidence at all.
    """
    if not config.KNOWN_ANOMALIES_CSV.exists():
        return pd.DataFrame(columns=REQUIRED_COLUMNS)

    df = pd.read_csv(config.KNOWN_ANOMALIES_CSV, dtype={"game_id": str})

    missing = [c for c in REQUIRED_COLUMNS if c not in df.columns]
    if missing:
        raise AnomalyRegistryError(
            f"{config.KNOWN_ANOMALIES_CSV} is missing required columns: "
            f"{missing}. The registry must record its own evidence."
        )

    for col in ("verification_source", "verified_on"):
        blank = df.loc[df[col].isna() | df[col].astype(str).str.strip().eq("")]
        if not blank.empty:
            raise AnomalyRegistryError(
                f"{len(blank)} registry row(s) have no {col}. An anomaly "
                f"without evidence cannot be accepted. Offending game_ids: "
                f"{list(blank['game_id'])}"
            )

    df["game_id"] = df["game_id"].astype(str).str.zfill(10)
    return df


def excused_game_ids(column: str) -> set:
    """
    Game IDs with a documented anomaly in a specific column.

    Scoped by column on purpose. A game excused for a bad PLUS_MINUS is not
    thereby excused for a bad GAME_ID or a missing result.
    """
    df = load_anomalies()
    if df.empty:
        return set()
    return set(df.loc[df["column"].eq(column), "game_id"])


def render_registry(df: pd.DataFrame = None) -> list:
    """Format the registry for inclusion in a validation report."""
    if df is None:
        df = load_anomalies()

    lines = ["DOCUMENTED DATA ANOMALIES", "-" * 25]
    if df.empty:
        lines.append("  Registry is empty. No anomalies have been excused.")
        return lines

    lines.append(f"  {len(df)} game(s) carry a documented, verified anomaly.")
    lines.append("  These are excused from the specific check named, and only")
    lines.append("  that check. Evidence is recorded for each.")
    lines.append("")
    for _, r in df.iterrows():
        lines.append(f"  {r['game_date']}  {r['matchup']}  "
                     f"[{r['column']}]  game_id {r['game_id']}")
        lines.append(f"    issue    : {r['issue']}")
        lines.append(f"    reported : {r['reported_value']}")
        for extra in ("verified_bos_pts", "verified_opp_pts",
                      "verified_margin", "implied_player_sum",
                      "expected_player_sum"):
            if extra in r.index and pd.notna(r[extra]):
                lines.append(f"    {extra:<9}: {r[extra]}")
        lines.append(f"    verified : {r['verification_source']} "
                     f"on {r['verified_on']}")
        lines.append(f"    action   : {r['resolution']}")
        lines.append("")
    return lines
